import type { Metadata } from "next";
import Link from "next/link";
import { twitterCard } from "@/lib/twitter-card";

import { marketIsReal, providerName } from "@/lib/market";
import { pageOg } from "@/lib/og-pages";
import { SITE } from "@/lib/site";

export const revalidate = 300;

export async function generateMetadata(): Promise<Metadata> {
  const live = await marketIsReal();
  return {
  title: "Terms, disclosures and privacy",
  description: live
    ? "Igitur is research output, not investment advice. Market data is third-party and may be delayed, there are no accounts and no tracking, claims are recorded only when you ask, and the site never requests a signature or a private key."
    : "Igitur is research output, not investment advice. The data is synthetic, there are no accounts and no tracking, claims are recorded only when you ask, and the site never requests a signature or a private key.",
  alternates: { canonical: "/legal" },
  openGraph: {
    url: "/legal",
    title: `Terms, disclosures and privacy — ${SITE.name}`,
    description: live
      ? "Not advice, third-party market data, no tracking, a public record you opt into, and the wallet rules — in plain language."
      : "Not advice, synthetic data, no tracking, a public record you opt into, and the wallet rules — in plain language.",
    images: [{ url: pageOg("legal"), width: 1200, height: 630 }],
  },
  twitter: twitterCard(pageOg("legal")),
  };
}

export default async function LegalPage() {
  // A disclosure page that describes the data has to read the data. Telling a
  // reader their prices are invented when they are not is as wrong as the
  // reverse, and this is the page people quote back at you.
  const live = await marketIsReal();
  return (
    <section className="shell pgtop" style={{ paddingBottom: "clamp(50px,7vw,90px)" }}>
      <span className="kick rv">Terms, disclosures and privacy</span>
      <h1 className="pg rv" style={{ marginTop: 12, maxWidth: "20ch" }}>
        The short version, in plain language.
      </h1>
      <div className="bento rv">
        <div className="cell c3">
          <h3>This is not investment advice</h3>
          <p className="p" style={{ marginTop: 8 }}>
            Igitur produces research output from a stated premise. It does not know your
            circumstances, your tax position, your time horizon or your capacity for loss. Nothing
            generated here is a recommendation to buy or sell any security, and no output should be
            treated as personalised advice.
          </p>
          <p className="p" style={{ marginTop: 10 }}>
            Speak to a licensed adviser in your jurisdiction before acting on anything you read
            here.
          </p>
        </div>
        <div className="cell c3">
          <h3>{live ? "Where the market data comes from" : "The data is synthetic"}</h3>
          {live ? (
            <>
              <p className="p" style={{ marginTop: 8 }}>
                Prices, market capitalisations, daily moves and performance series come from{" "}
                {providerName()}, a third-party vendor. That data may be delayed, may be revised,
                and is provided without any warranty of accuracy by them or by us. It is published
                here for research, not for trading, and no figure on this site should be relied on
                as a record of what a security actually traded at.
              </p>
              <p className="p" style={{ marginTop: 10 }}>
                Where the vendor does not cover a holding, the figure shown is generated rather than
                real, and the page says so beside it. Past performance, real or otherwise, does not
                predict future returns.
              </p>
            </>
          ) : (
            <p className="p" style={{ marginTop: 8 }}>
              Every price, market capitalisation, daily move and performance series on this
              prototype is generated by a formula from the ticker text. None of it is real market
              data, none of it updates, and none of it should be used to make a decision about
              anything.
            </p>
          )}
          <p className="p" style={{ marginTop: 10 }}>
            Conviction scores are editorial opinion, described in full on the methodology page.
          </p>
        </div>
        <div className="cell c3">
          <h3>Privacy</h3>
          <p className="p" style={{ marginTop: 8 }}>
            No account, no login, no cookies, no analytics. What you type stays in your browser.
            Session history is held in memory and disappears when you close the tab.
          </p>
          <p className="p" style={{ marginTop: 10 }}>
            One exception, and it only happens when you ask for it. Pressing{" "}
            <b>Put this on the record</b> writes your claim and that day&rsquo;s date to a{" "}
            <Link href="/ledger">public page</Link>. Stored with it: the claim, the date, the theme
            it matched and the universe version. Not stored: your name, your address, any
            identifier, or anything that could connect the claim back to you. Because nothing links
            it to you, there is no account through which it could be withdrawn — a record that could
            be deleted once it went badly would not be a record. Do not put anything in a premise
            you would not publish.
          </p>
          <p className="p" style={{ marginTop: 10 }}>
            Book addresses encode your premise in the URL, so anything you share is visible to
            whoever holds the link.
          </p>
        </div>
        <div className="cell c3">
          <h3>Token and wallet</h3>
          <p className="p" style={{ marginTop: 8 }}>
            The token is not deployed and nothing on this site is an offer to sell it. Utilities
            described on the token page are stated intentions and may change or never ship. Tokens
            can be volatile and can lose all value.
          </p>
          <p className="p" style={{ marginTop: 10 }}>
            Connecting a wallet here reads your public address only. This site never requests a
            signature, a transaction, a seed phrase or a private key, and never will. Any page that
            does is not us.
          </p>
        </div>
        <div className="cell c3">
          <h3>Risk</h3>
          <p className="p" style={{ marginTop: 8 }}>
            Thematic portfolios are concentrated by construction. They carry more single-name risk,
            more sector risk and more drawdown than a broad index fund, and a correct thesis can
            still lose money on a bad entry or a long enough horizon.
          </p>
          <p className="p" style={{ marginTop: 10 }}>
            Past performance, real or simulated, tells you nothing about future returns.
          </p>
        </div>
      </div>
    </section>
  );
}
