import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms, disclosures and privacy",
  description:
    "Premise is research output, not investment advice. The data is synthetic, there is no account or tracking, and the site never requests a signature or a private key.",
  alternates: { canonical: "/legal" },
  openGraph: {
    url: "/legal",
    title: "Terms, disclosures and privacy — Premise",
    description: "Not advice, synthetic data, no tracking, and the wallet rules — in plain language.",
  },
};

export default function LegalPage() {
  return (
    <section className="shell pgtop" style={{ paddingBottom: "clamp(50px,7vw,90px)" }}>
      <span className="kick rv">Terms, disclosures and privacy</span>
      <h1 className="pg rv" style={{ marginTop: 12, maxWidth: "20ch" }}>
        The short version, in plain language.
      </h1>
      <div className="bento rv">
        <div className="cell c3">
          <h3>This is not investment advice</h3>
          <p className="p" style={{ marginTop: 8 }}>
            Premise produces research output from a stated premise. It does not know your
            circumstances, your tax position, your time horizon or your capacity for loss. Nothing
            generated here is a recommendation to buy or sell any security, and no output should be
            treated as personalised advice.
          </p>
          <p className="p" style={{ marginTop: 10 }}>
            Speak to a licensed adviser in your jurisdiction before acting on anything you read
            here.
          </p>
        </div>
        <div className="cell c3">
          <h3>The data is synthetic</h3>
          <p className="p" style={{ marginTop: 8 }}>
            Every price, market capitalisation, daily move and performance series on this prototype
            is generated by a formula from the ticker text. None of it is real market data, none of
            it updates, and none of it should be used to make a decision about anything.
          </p>
          <p className="p" style={{ marginTop: 10 }}>
            Conviction scores are editorial opinion, described in full on the methodology page.
          </p>
        </div>
        <div className="cell c3">
          <h3>Privacy</h3>
          <p className="p" style={{ marginTop: 8 }}>
            No account, no login, no cookies, no analytics. What you type stays in your browser.
            Session history is held in memory and disappears when you close the tab.
          </p>
          <p className="p" style={{ marginTop: 10 }}>
            Book addresses encode your premise in the URL, so anything you share is visible to
            whoever holds the link.
          </p>
        </div>
        <div className="cell c3">
          <h3>Token and wallet</h3>
          <p className="p" style={{ marginTop: 8 }}>
            The token is not deployed and nothing on this site is an offer to sell it. Utilities
            described on the token page are stated intentions and may change or never ship. Tokens
            can be volatile and can lose all value.
          </p>
          <p className="p" style={{ marginTop: 10 }}>
            Connecting a wallet here reads your public address only. This site never requests a
            signature, a transaction, a seed phrase or a private key, and never will. Any page that
            does is not us.
          </p>
        </div>
        <div className="cell c3">
          <h3>Risk</h3>
          <p className="p" style={{ marginTop: 8 }}>
            Thematic portfolios are concentrated by construction. They carry more single-name risk,
            more sector risk and more drawdown than a broad index fund, and a correct thesis can
            still lose money on a bad entry or a long enough horizon.
          </p>
          <p className="p" style={{ marginTop: 10 }}>
            Past performance, real or simulated, tells you nothing about future returns.
          </p>
        </div>
      </div>
    </section>
  );
}
