/**
 * The X post banner.
 *
 * Built from the site's own tokens, mark and allocation bar rather than
 * redrawn, so the image and the page a reader lands on are recognisably the
 * same object. The holdings are generated by lib/generator at build time, not
 * typed in: a banner advertising a tool that shows real weights should not
 * itself carry invented ones.
 *
 *   node brand/x/make-banner.mjs
 */
import { chromium } from "playwright";
import { readdirSync, writeFileSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");

// Inter, exactly as next/font serves it to the site. Every subset is declared
// under one family and the browser takes whichever covers the glyph, which
// avoids guessing which hashed file is the Latin one.
const MEDIA = join(ROOT, ".next", "static", "media");
const faces = readdirSync(MEDIA)
  .filter((f) => f.endsWith(".woff2"))
  .map((f) => `@font-face{font-family:Inter;src:url("file://${join(MEDIA, f)}") format("woff2");font-weight:100 900;font-display:block}`)
  .join("\n");

const book = JSON.parse(readFileSync(join(HERE, "book.json"), "utf8"));

const W = 1600;
const H = 900;

const bar = book.holdings
  .map((h) => {
    const cls = h.lead ? "lead" : h.ballast ? "bal" : "";
    return `<div class="${cls}" style="flex:${h.pct}">
        <b>${h.t}</b><i>${h.pct}%</i>
      </div>`;
  })
  .join("");

const html = `<!doctype html><meta charset="utf-8"><style>
${faces}
*{margin:0;padding:0;box-sizing:border-box}
:root{
  --bg:#0A0A0B; --fg:#FAFAFA; --fg-2:#9E9EA6; --fg-3:#8A8A92; --fg-4:#7A7A82;
  --ac:#7C8CFF; --ac-2:#AEB6FF; --bd:rgba(255,255,255,.068);
}
html,body{width:${W}px;height:${H}px}
body{background:var(--bg);font-family:Inter,system-ui,sans-serif;color:var(--fg);
  -webkit-font-smoothing:antialiased;position:relative;overflow:hidden}

/* The same two washes the site paints behind every page. */
.glow{position:absolute;inset:0;
  background:radial-gradient(900px 560px at 46% -10%,rgba(124,140,255,.17),transparent 64%),
             radial-gradient(640px 460px at 92% 8%,rgba(160,140,255,.08),transparent 62%)}
.grain{position:absolute;inset:0;opacity:.30;mix-blend-mode:overlay;
  background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='160' height='160'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='3'/%3E%3C/filter%3E%3Crect width='160' height='160' filter='url(%23n)'/%3E%3C/svg%3E")}

.wrap{position:relative;z-index:2;height:100%;padding:74px 86px 66px;
  display:flex;flex-direction:column;justify-content:space-between}

/* The mark: two premises above, the conclusion below. Same proportions as
   brand/igitur-mark.svg — the second premise is 0.70 of the first. */
.brand{display:flex;align-items:center;gap:18px}
.mark{display:flex;flex-direction:column;gap:6.5px;width:44px}
.mark .top{display:flex;gap:3.2px;height:9px}
.mark .p1{width:22.8px;background:rgba(255,255,255,.36);border-radius:4.5px}
.mark .p2{width:16px;background:var(--ac);border-radius:4.5px}
.mark .concl{width:44px;height:12.5px;background:var(--fg);border-radius:6.25px}
.name{font-size:34px;font-weight:600;letter-spacing:-.025em}
.dot{width:4px;height:4px;border-radius:50%;background:var(--fg-4);margin:0 4px}
.url{font-size:21px;color:var(--fg-4);letter-spacing:.01em}

h1{font-size:96px;line-height:1.02;letter-spacing:-.04em;font-weight:600;max-width:24ch}
h1 em{font-style:normal;color:var(--ac-2)}
.sub{margin-top:26px;font-size:29px;line-height:1.4;color:var(--fg-2);max-width:none;width:1180px;font-weight:350}

.proof{display:flex;flex-direction:column;gap:18px}
.kick{font-size:15px;letter-spacing:.14em;color:var(--fg-4);text-transform:uppercase;margin-right:18px}
.claim{font-size:25px;color:var(--fg);font-weight:350;display:flex;align-items:baseline;margin-bottom:2px}


.bar{display:flex;gap:5px;height:168px}
.bar>div{position:relative;display:flex;flex-direction:column;justify-content:flex-end;
  padding:12px 13px 13px;min-width:0;overflow:hidden;border-radius:11px;
  background:linear-gradient(180deg,rgba(255,255,255,.10),rgba(255,255,255,.035));
  box-shadow:inset 0 0 0 1px rgba(255,255,255,.075)}
.bar .lead{background:linear-gradient(180deg,#fff,#C9CEFF 55%,#8B95E8);color:#0A0A0B;
  box-shadow:inset 0 0 0 1px rgba(255,255,255,.6),0 0 46px -8px rgba(174,182,255,.6)}
.bar .bal{background:linear-gradient(180deg,rgba(124,140,255,.5),rgba(76,88,180,.28));
  box-shadow:inset 0 0 0 1px rgba(124,140,255,.35)}

.bar b{font-size:17px;font-weight:600;letter-spacing:-.01em;display:block;white-space:nowrap}
.bar i{font-style:normal;font-size:15px;opacity:.66;display:block;margin-top:3px}
.bar .lead b,.bar .lead i{opacity:1}
.bar .lead i{opacity:.62}

.foot{display:flex;justify-content:space-between;align-items:baseline;gap:40px;
  border-top:1px solid var(--bd);padding-top:22px;font-size:20px}
.foot .why{color:var(--fg-2);font-weight:350}
.foot .why b{color:var(--fg);font-weight:600;margin-right:14px;letter-spacing:-.01em}
.foot .meta{color:var(--fg-4);white-space:nowrap;font-size:19px}
</style>
<div class="glow"></div><div class="grain"></div>
<div class="wrap">
  <div class="brand">
    <div class="mark">
      <div class="top"><div class="p1"></div><div class="p2"></div></div>
      <div class="concl"></div>
    </div>
    <div class="name">Igitur</div>
    <div class="dot"></div>
    <div class="url">igitur.xyz</div>
  </div>

  <div>
    <h1>Write what you believe.<br><em>See what it holds.</em></h1>
    <p class="sub">One sentence about the next decade becomes a weighted portfolio — and every
      weight carries the reason it earned its size.</p>
  </div>

  <div class="proof">
    <p class="claim"><span class="kick">From one premise</span>“${book.premise}”</p>
    <div class="bar">${bar}</div>
    <div class="foot">
      <span class="why"><b>${book.holdings[0].t} ${book.holdings[0].pct}%</b>${book.holdings[0].why}</span>
      <span class="meta">${book.theme} · widths are weights</span>
    </div>
  </div>
</div>`;

const file = join(HERE, "banner.html");
writeFileSync(file, html);

const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await browser.newPage({ viewport: { width: W, height: H }, deviceScaleFactor: 2 });
await page.goto("file://" + file);
await page.evaluate(() => document.fonts.ready);
await page.waitForTimeout(400);
await page.screenshot({ path: join(HERE, "x-post-banner.png") });
await browser.close();
console.log("brand/x/x-post-banner.png  " + W * 2 + "×" + H * 2);
